---
deployment:
  tasks:
    - export DEPLOYPATH=/home/azwywnto/apps/shopifysectiongen/standalone-app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R ./* $DEPLOYPATH/
    - /bin/chmod -R 755 $DEPLOYPATH
