---
deployment:
  tasks:
    - cd $HOME/repositories/shopify-section-generator-live && /usr/local/bin/npm install --production=false
    - cd $HOME/repositories/shopify-section-generator-live && /usr/local/bin/npm run build
    - /bin/rm -rf $HOME/public_html/*
    - /bin/cp -R $HOME/repositories/shopify-section-generator-live/out/* $HOME/public_html/
    - /bin/cp -R $HOME/repositories/shopify-section-generator-live/out/.htaccess $HOME/public_html/ 2>/dev/null || true
