---
deployment:
  tasks:
    - export DEPLOYPATH=/home/azwywnto/apps/shopifysectiongen/standalone-app
    - /bin/mkdir -p $DEPLOYPATH
    - cd /home/azwywnto/repositories/shopify-section-generator/standalone-app
    - /bin/cp -R * $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -R .[^.]* $DEPLOYPATH/ 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH

