---
deployment:
  tasks:
    - export DEPLOYPATH=/home/azwywnto/apps/shopifysectiongen/standalone-app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -R .[^.]* $DEPLOYPATH/ 2>/dev/null || true

