---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - export REPOPATH=$HOME/repositories/shopify-section-generator-live
    - /bin/sh -c "cd $REPOPATH && npm install && npm run build"
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R $REPOPATH/out/* $DEPLOYPATH/ 2>/dev/null || true
